title: PE Tools
description: Portable executable (PE) manipulation toolkit
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist

github:
  zip_url: https://github.com/petoolse/petools/releases
  tar_url: https://github.com/petoolse/petools/releases
  whatsnew_url: /petools/#whats-new-in-recent-major-releases
